### ISSUE TITLE
Example of EPUB

### ISSUE THREAD

**Issue by dxcore35** [Aftnet/ComicPub#20]
Can you provide some example of the output in epub? (some free comix).
Just to see what the tool is capable to do, how the images are show, and what metadata are inside.

**Comment by AnthroHeader** [comment]
It's a good idea, but do you have a good source for that?

In most cases (and all the free comics I am aware of), even if a comic is available for reading for free redistribution is not allowed.

**Comment by dxcore35** [comment]
:{ I don't know actually, that is funny. There is no open-source comix
