### ISSUE TITLE
CPubMake skips the first image when using -d flag

### ISSUE THREAD

**Issue by wizo06** [Aftnet/ComicPub#21]
I have 195 images inside the folder `firstvolume`. When I run the following command:
```
./CPubMake -d "firstvolume" -o "output.epub"
```
I get this output:
```
Generating output.epub
Adding image 194/194
```
And sure enough, when I open the `output.epub` file, the first image from the `firstvolume` folder is not included.

**Comment by AnthroHeader** [comment]
That's because in that case the first page is set as the cover, and not all epub readers display it when reading (will show up in the library screen instead).

**Comment by wizo06** [comment]
I've tried both scenarios
```
./CPubMake -d "firstvolume" -o "output.epub"
./CPubMake -d "firstvolume" -c "firstvolume/001.jpg" -o "output.epub"
```
And in both scenarios, the first image of the folder is skipped. Is this intended?

**Comment by AnthroHeader** [comment]
Try extracting the generated epub (they are just zip files with a different extension), then check in OBEPS folder: is Cover.jpg the first page you are missing?

**Comment by wizo06** [comment]
That is correct. I extracted both generated epub files, and checked their respective Cover.jpg. They're both the first page that's missing.

It seems like `CPubMake` implicitly uses the first image of the folder as the cover (if `-c` flag is not provided), and the cover image is not included as the first page of the epub. Is this an intended feature?

If so, maybe a workaround for me is to make a copy of the first image `001.jpg` as `000.jpg`. This way, `000.jpg` will be used as cover, and `001.jpg` will still be included as the first page of the epub.

**Comment by AnthroHeader** [comment]
Yes, that is an intended feature. In general, the cover is not meant to be also the firts page of an ebook: if people author books with wide images for two pages spreads adding an extra pages messes everything up.

For your situation, you can use the workaround you mentioned.
